import {NgModule} from '@angular/core';
import {
    MatSidenavModule,
    MatToolbarModule,
    MatIconModule,
    MatListModule,
    MatSelectModule,

   // MatToolbarModule, 
         MatFormFieldModule, 
         MatInputModule, 
         MatOptionModule, 
   //      MatSelectModule, 
    //     MatIconModule, 
         MatButtonModule, 
         MatCardModule, 
         MatTableModule, 
         MatDividerModule, 
         MatSnackBarModule,
         MatAutocompleteModule,
         MatBadgeModule,
         MatBottomSheetModule,
         MatButtonToggleModule,
         MatCheckboxModule,
         MatChipsModule,
         MatDatepickerModule,
         MatDialogModule,
         MatExpansionModule,
         MatGridListModule,
         MatMenuModule,
         MatNativeDateModule,
         MatPaginatorModule,
         MatProgressBarModule,
         MatProgressSpinnerModule,
         MatRadioModule,
         MatRippleModule,
         MatSliderModule,
         MatSlideToggleModule,
         MatSortModule,
         MatStepperModule,
         MatTabsModule,
         MatTooltipModule,
         MatTreeModule
} from '@angular/material';

@NgModule({
    imports:[
        MatSidenavModule,
        MatToolbarModule,
        MatIconModule, 
        MatListModule,
        MatSelectModule,

     //   MatToolbarModule, 
         MatFormFieldModule, 
         MatInputModule, 
         MatOptionModule, 
     //    MatSelectModule, 
      //   MatIconModule, 
         MatButtonModule, 
         MatCardModule, 
         MatTableModule, 
         MatDividerModule, 
         MatSnackBarModule, MatAutocompleteModule,
         MatBadgeModule,
         MatBottomSheetModule,
         MatButtonToggleModule,
         MatCheckboxModule,
         MatChipsModule,
         MatDatepickerModule,
         MatDialogModule,
         MatExpansionModule,
         MatGridListModule,
         MatMenuModule,
         MatNativeDateModule,
         MatPaginatorModule,
         MatProgressBarModule,
         MatProgressSpinnerModule,
         MatRadioModule,
         MatRippleModule,
         MatSliderModule,
         MatSlideToggleModule,
         MatSortModule,
         MatStepperModule,
         MatTabsModule,
         MatTooltipModule,
         MatTreeModule
    ],
    exports:[
        MatSidenavModule,
        MatToolbarModule,
        MatIconModule,
        MatListModule,
        MatSelectModule,

     //   MatToolbarModule, 
         MatFormFieldModule, 
         MatInputModule, 
         MatOptionModule, 
     //    MatSelectModule, 
     //    MatIconModule, 
         MatButtonModule, 
         MatCardModule, 
         MatTableModule, 
         MatDividerModule, 
         MatSnackBarModule,
         MatAutocompleteModule,
         MatBadgeModule,
         MatBottomSheetModule,
         MatButtonToggleModule,
         MatCheckboxModule,
         MatChipsModule,
         MatDatepickerModule,
         MatDialogModule,
         MatExpansionModule,
         MatGridListModule,
         MatMenuModule,
         MatNativeDateModule,
         MatPaginatorModule,
         MatProgressBarModule,
         MatProgressSpinnerModule,
         MatRadioModule,
         MatRippleModule,
         MatSliderModule,
         MatSlideToggleModule,
         MatSortModule,
         MatStepperModule,
         MatTabsModule,
         MatTooltipModule,
         MatTreeModule
    ]
})

export class MaterialModule{}